-- =============================================================
-- Province Games — PostgreSQL Schema
-- backend/database/schema.sql
--
-- Run once to set up the database:
--   psql -d province_games -f schema.sql
--
-- All tournament data is stored as JSONB so the frontend's
-- tournament object maps 1:1 without an ORM translation layer.
-- Indexes cover the access patterns: by id, by share_code,
-- by updated_at (for sync queries), by status.
-- =============================================================

-- Enable extension for generated UUIDs if needed
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ── Tournaments ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tournaments (
  -- Primary identifier — matches the id field generated by the frontend
  id              TEXT        PRIMARY KEY,

  -- 6-8 char uppercase share code for viewer access
  share_code      TEXT        NOT NULL UNIQUE,

  -- Denormalised columns for fast list queries (avoids JSONB parsing)
  name            TEXT        NOT NULL DEFAULT '',
  game            TEXT        NOT NULL DEFAULT 'mobile_legends',
  format          TEXT        NOT NULL DEFAULT 'single_elimination',
  status          TEXT        NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active', 'done', 'cancelled')),

  -- Timestamps stored as epoch milliseconds (matches JS Date.now())
  created_at      BIGINT      NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()) * 1000,
  updated_at      BIGINT      NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()) * 1000,

  -- Full tournament object — bracket data, teams, matches, standings
  data            JSONB       NOT NULL DEFAULT '{}',

  -- Soft delete — keeps data accessible for sync but hides from list
  deleted         BOOLEAN     NOT NULL DEFAULT FALSE,
  deleted_at      BIGINT
);

-- Index for share code lookups (view.html)
CREATE INDEX IF NOT EXISTS idx_tournaments_share_code
  ON tournaments (share_code)
  WHERE deleted = FALSE;

-- Index for sync queries (fetch everything updated after a timestamp)
CREATE INDEX IF NOT EXISTS idx_tournaments_updated_at
  ON tournaments (updated_at DESC)
  WHERE deleted = FALSE;

-- Index for status filtering
CREATE INDEX IF NOT EXISTS idx_tournaments_status
  ON tournaments (status)
  WHERE deleted = FALSE;

-- GIN index on JSONB for potential full-text search on team names
CREATE INDEX IF NOT EXISTS idx_tournaments_data_gin
  ON tournaments USING GIN (data);


-- ── Sync Log ──────────────────────────────────────────────────
-- Records every write operation for conflict resolution and audit.
-- The frontend uses last-write-wins; the server stores the log
-- so we can reconstruct history if needed.
CREATE TABLE IF NOT EXISTS sync_log (
  id              BIGSERIAL   PRIMARY KEY,
  tournament_id   TEXT        NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
  operation       TEXT        NOT NULL CHECK (operation IN ('create', 'update', 'delete')),
  client_id       TEXT,       -- optional: identify which device made the change
  payload_diff    JSONB,      -- what changed (for debugging, not required for functionality)
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sync_log_tournament
  ON sync_log (tournament_id, created_at DESC);


-- ── Connected Clients (WebSocket rooms) ───────────────────────
-- Tracks which tournament IDs have active subscribers.
-- Cleaned up on server restart; the WS server manages this in-memory,
-- but this table lets you see current activity via SQL.
CREATE TABLE IF NOT EXISTS ws_connections (
  connection_id   TEXT        PRIMARY KEY,
  tournament_id   TEXT,
  connected_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_ping_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  client_type     TEXT        CHECK (client_type IN ('admin', 'viewer'))
);

CREATE INDEX IF NOT EXISTS idx_ws_connections_tournament
  ON ws_connections (tournament_id);


-- ── Helper views ──────────────────────────────────────────────

-- Active tournaments list (for dashboard queries)
CREATE OR REPLACE VIEW active_tournaments AS
SELECT
  id,
  share_code,
  name,
  game,
  format,
  status,
  created_at,
  updated_at,
  data -> 'teams' AS teams,
  jsonb_array_length(COALESCE(data -> 'teams', '[]'::jsonb)) AS team_count
FROM tournaments
WHERE deleted = FALSE
ORDER BY updated_at DESC;


-- ── Seed data for development ──────────────────────────────────
-- (Commented out — run manually or via seed.sql)
-- INSERT INTO tournaments (id, share_code, name, game, format, data)
-- VALUES ('ML-DEV-001', 'MLDEV1', 'Dev Test Tournament', 'mobile_legends',
--         'groups_double_elim', '{}');
